### ISSUE TITLE
wandb error

### ISSUE THREAD

**Issue by haoyao0131** [LandskapeAI/triplet-attention#10]
Hi,
I came across the following error. Does anyone has similar experience?
Thanks. 
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/40881644/97776937-a1608b00-1b29-11eb-9fa7-f8c3d9fd88f3.png">

**Comment by iyaja** [comment]
I haven't seen this error before, but I don't think it's related to triplet attention. Is this something that works fine without triplet attention? Are you using one of our training scripts, or did you make modifications?

My guess is that the issue might be related to `wandb.watch(model)` if you're using that function. Maybe try removing that if you can.

**Comment by haoyao0131** [comment]
Thanks for your reply. I modified the code to apply my own dataset. And it works when I remove wandb function.

**Comment by digantamisra98** [comment]
Great, thanks for notifying us.

**Comment by AdarshSantoria** [comment]
@haoyao0131 Do you have fine tuning code without wandb?
