### ISSUE TITLE
No multiprocessing option

### ISSUE THREAD

**Issue by haoyao0131** [LandskapeAI/triplet-attention#11]
Hi,
For the usage, I didn't find the way to enable to multi-GPU training option. I attached one screenshot.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/40881644/97796532-4170ef80-1bd0-11eb-82e0-8920ea477e01.png">

**Comment by iyaja** [comment]
We have instructions for running multi-gpu training jobs on our [README](https://github.com/LandskapeAI/triplet-attention#single-node-multiple-gpus). Let me know if that doesn't work for some reason.

**Comment by haoyao0131** [comment]
It doesn't work. I didn't modify the original code. The error is below.

<img width="951" alt="image" src="https://user-images.githubusercontent.com/40881644/97811852-0a332a80-1c32-11eb-9e47-fcebbf7bdeb8.png">

**Comment by iyaja** [comment]
Ah, sorry. The instructions on the README are for using the script in our [`imagenet` repo](https://github.com/LandskapeAI/imagenet).

The training script you're using automatically uses PyTorch's `nn.DataParallel` for multi-gpu training with the `--ngpu` argument. Could you check your GPU usage with `nvidia-smi` to confirm that?

**Comment by haoyao0131** [comment]
Yes, the nn.DataParallel works. But it is not better than NCCL backend for multi-processing distributed training, right? So do you have any version that could use the instructions on the README?

**Comment by iyaja** [comment]
Yes, NCCL is generally the recommended approach. We have code for distributed training that uses NCCL on the [LandskapeAI/imagenet repo](https://github.com/LandskapeAI/imagenet). Since triplet attention is just a module, you can plug it in to the resnet defined there.
