### ISSUE TITLE
The weights in google drive is demage!!!

### ISSUE THREAD

**Issue by shaojiestar** [LandskapeAI/triplet-attention#14]
hello my friend!!!
When I download the weight in your readme.md file ,a .rar file was downloaded but I can't  open it or unzip it.
the error is :
![image](https://user-images.githubusercontent.com/30548709/101237044-c0e26900-3710-11eb-9643-eaec7dbdad06.png)

**Comment by shaojiestar** [comment]
so can you give me the pth file by email?
2422656558@qq.com
thank you !!!

**Comment by iyaja** [comment]
I've faced this issue before with other models. Actually, you _don't_ need to untar the file we provide on Google drive. You can just write something like

```python
torch.load("RESNET50_PCAM_IMAGENET_model_best.tar")
```

Take a look at our scripts and commands mentioned in the README for a clear example, and let me know if you're still facing issues after this.
