### ISSUE TITLE
怎么修改能一键替换SE 和CBAM

### ISSUE THREAD

**Issue by cendelian** [LandskapeAI/triplet-attention#17]
如题，有没有方法直接一键替换SE和CBAM

triplet_attention模块初始化并不是与SE一样是channels参数

```
# SE attention
class SE(nn.Module):
    def __init__(self, in_channels, channels, se_ratio=12):
        super(SE, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.fc = nn.Sequential(
            nn.Conv2d(in_channels, channels // se_ratio, kernel_size=1, padding=0),
            nn.BatchNorm2d(channels // se_ratio),
            nn.ReLU(inplace=True),
            nn.Conv2d(channels // se_ratio, channels, kernel_size=1, padding=0),
            nn.Sigmoid()
        )

    def forward(self, x):
        y = self.avg_pool(x)
        y = self.fc(y)
        return x * y
```

**Comment by digantamisra98** [comment]
@cendelian SE and CBAM can be directly replaced with Triplet. CBAM, SE and Triplet are dimension preserving modules and thus don't affect the number of channels of the input tensor. SE and CBAM requires the channel parameter because it has a MLP structure which is not present in Triplet Attention. Hopefully this clarifies.

**Comment by cendelian** [comment]
> @cendelian SE and CBAM can be directly replaced with Triplet. CBAM, SE and Triplet are dimension preserving modules and thus don't affect the number of channels of the input tensor. SE and CBAM requires the channel parameter because it has a MLP structure which is not present in Triplet Attention. Hopefully this clarifies.

thanks for you reply.
and if I use Triplet to replace SE or CBAM.
Does the pretrain can use?
for example. I use resnet with SE attention, but when I replace SE with triplet, the resnet pretrain can use?
maybe i need train resnet with triplet from scrach?

**Comment by digantamisra98** [comment]
@cendelian No you can't use a SE or CBAM pretrained network and replace them with Triplet. You need to retrain the network with Triple Attention from scratch. But we have provided the weights for pretrained networks which you can use.
