### ISSUE TITLE
预训练权重

### ISSUE THREAD

**Issue by ZJUTSong** [LandskapeAI/triplet-attention#2]
我这边使用res2net的话，看到您这边没有对应的res2net+triplet_attentation预训练权重，会有影响吗？

**Comment by digantamisra98** [comment]
Hi, we didn't train a Res2Net with triplet attention and therefore don't have any corresponding training weights. We plan to train Efficient Net and Res2Net backbones ahead in the near future. However, we are strongly confident that training a Res2Net with Triplet attention won't cause any issues and should provide performance boost as highlighted by our existing results. Feel free to notify us in case of any issues regarding Triplet's performance in Res2Net. Thanks!
