### ISSUE TITLE
Hi,I wanna ask that how to calculate the AP value of. 

### ISSUE THREAD

**Issue by sunhao123456789** [LandskapeAI/triplet-attention#20]
Hi,I wanna ask that how to calculate the AP value of.  I can't find it in the code. And I don't know  how  to calculate the Recall value of.
Thank you very much.

**Comment by digantamisra98** [comment]
@sunhao123456789 Apologies for the delay in response, we use [MMDetection](https://github.com/open-mmlab/mmdetection) for all the metrics reported in the object detection section of the paper.
