### ISSUE TITLE
Triplet Attention can be applied to EfficientNet in place SE? 

### ISSUE THREAD

**Issue by osivaz61** [LandskapeAI/triplet-attention#22]

**Comment by digantamisra98** [comment]
@osivaz61 Yes it can be. It should be just a drop in replacement.

**Comment by osivaz61** [comment]
> @osivaz61 Yes it can be. It should be just a drop in replacement.
I am sorry but I could not understand what you say exactly.
You tried to apply TA to Effs and finally get drop in performance?

**Comment by digantamisra98** [comment]
@osivaz61 Your question was whether TA can be used in Efficient Net in place of SE? And the answer is yes. Regarding whether it gets better or worse performance, we didn't do any experiments on Efficient Net to confirm.
