### ISSUE TITLE
mmdetection_fasterrcnn

### ISSUE THREAD

**Issue by ZJUTSong** [LandskapeAI/triplet-attention#7]
hello, i applied triple_attention on fasterrcnn using mmdetection, the problem is inference speed becomes very slow ， about twice slower，why this happens？  And  where is  the code  you applied trilet_attention on fasterrcnn using mmdetection？i‘d like to learn some.  Thanks~

**Comment by iyaja** [comment]
Thanks for trying it out. It's expected that triplet attention would incur a performance cost, but could you share more info? What batch size, image size, CPU, accelerator, etc. are you using?

We're planning to release the mmdetection code soon, but the implementation is relatively straightforward. All we do is add triplet the usual way into a model definition identical to the default ResNet provided in mmdetection. The repo has a guide on how to do this: https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_models.md

**Comment by ZJUTSong** [comment]
Thans for yor patiently help ！
batch_size=1, img_size=(1400, 840), GPU:nvidia1080ti.   
 The baseline inference speed about  13.8FPS, but decreased to 6.7FPS after  i used triplet_attentation, 
i added the triplet block on the third conv in every Bottleneck of res2net_50.
Also, i'd like to know if i have no pretrained backbone weights, the model  will be bad？ i have res2net pretrained model, but for triplet_block, i just iniltialized it.

**Comment by digantamisra98** [comment]
@ZJUTSong yes we expect the introduction of triplet attention will cause a drop in inference speed. We are planning to optimize it further. Additionally, we wouldn't advise to use a pretrained backbone and initialize triplet within it. As per our understanding, training from scratch would be a much better route. Thanks!
