### ISSUE TITLE
data loader issue in the training stage

### ISSUE THREAD

**Issue by Fly-dream12** [LandskapeAI/triplet-attention#8]
Thanks for your code!
When I try to add this attention mechanism into the resnet backbone and train a detection network, the error appears as:

 File "anaconda3/envs/maskrcnn/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 63, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 13791) is killed by signal: Aborted. 

The batch size and num_workers have been set as 1 and it stills goes wrong.
Could you give some suggestions?

**Comment by iyaja** [comment]
Could you share more info about your setup? Specifically:

- What devices are you using?
- Which example are you trying to run?
- How much memory is available?
- Are you running the default examples, or did you make any modifications?

**Comment by Fly-dream12** [comment]
1080ti
I just use the backbone structure into my own model
11G
I make some modifications and did not use the default examples




On 10/20/2020 12:59, Ajay Arasanipalai wrote:

Could you share more info about your setup? Specifically:

What devices are you using?
Which example are you trying to run?
How much memory is available?
Are you running the default examples, or did you make any modifications?

**Comment by iyaja** [comment]
@Fly-dream12 t's going to be a little harder to debug then. Could you share your code?

I'm not sure if this is an issue related to triplet attention specifically.

**Comment by digantamisra98** [comment]
@Fly-dream12 based on similar error's discussion from PyTorch issues, it doesn't seem to be an error associated to Triplet Attention. Please go through this [thread](https://github.com/pytorch/pytorch/issues/8976). Thanks!

**Comment by Fly-dream12** [comment]
Thanks, there exist some bug in my dataloader and I have fixed it. @digantamisra98 @iyaja 
Meanwhile, could you provide the example code of gradcam++ ?

**Comment by digantamisra98** [comment]
@Fly-dream12 we will upload the gradcam++ code this week.

**Comment by iyaja** [comment]
@Fly-dream12 I just added the GradCAM notebook [here](https://github.com/LandskapeAI/triplet-attention/blob/master/gradcam.ipynb).

Create a new issue if you're facing issues running the code there. Note that you need to have the pretrained models ready for this, and you need the [CBAM code](https://github.com/Jongchan/attention-module) as well if you want to generate the exact plots we have in the paper.
